name: matertino_radio
description: A Simple Custom Radio Group widgets for Flutter with a search option.
version: 1.0.1
homepage: https://github.com/ukieTux/flutter_radio_group

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  flutter_test:
    sdk: flutter
